- name: Setting up MariaDB on DB and Demo Server
  hosts: db_server, demo_server
  become: yes
  vars:
    mysql_root_pswd: "MySecurePassword" # change this before execute
  roles:
    - { role: mariadb, tags: mariadb }

- name: Middleware installation on UAT, PROD, and Demo servers
  hosts: uat_server, prod_server, demo_server
  become: yes
  vars:
    ioncube_download_url: "https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz"
    ioncube_tarfile: "ioncube_loaders.tar.gz"
  roles:
    - { role: dependencies, tags: dependencies }
    - { role: php, tags: php }
    - { role: ioncube, tags: ioncube }
    - { role: rabbitmq, tags: rabbitmq }
    - { role: final_config, tags: final_config }